[package]
name = "pybindings"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true
readme.workspace = true
license-file.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pybindings"
test = false
doctest = false

[dependencies]
pyo3 = { workspace = true, "features" = ["abi3-py310"] }
rayon = { workspace = true }
clap = { workspace = true }
composition = { path = "../composition" }
kmer = { path = "../kmer" }
