[package]
name = "counter"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = { workspace = true }
kmer = { path = "../kmer" }
ktio = { path = "../ktio" }
rayon = { workspace = true }
scc = { workspace = true }

[lib]
doctest = false
