[package]
name = "coverage"
version.workspace = true
edition.workspace = true
authors.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ktio = { path = "../ktio" }
kmer = { path = "../kmer" }
counter = { path = "../counter" }
rayon = { workspace = true }
scc = { workspace = true, features = ["serde"] }

[lib]
doctest = false
